### ISSUE TITLE
gcc version when running setup.py

### ISSUE THREAD

**Issue by forwiat** [cantabile-kwok/VoiceFlow-TTS#2]
"cd model/monotonic_align
python setup.py build_ext --inplace"
wonder which gcc version when compile this code

**Comment by cantabile-kwok** [comment]
I am using version 8.4.0, but I guess earlier ones will also work. This `monotonic_align` part is borrowed from [GlowTTS](https://github.com/jaywalnut310/glow-tts)

**Comment by forwiat** [comment]
yeah, but now I solved it.
I attempt update gcc to 8.4.0, but error still occurs.
Maybe because of high python version. (Python 3.9.0 when compile in anaconda, error info: /bin/ld: this linker was not configured to use sysroots). Ant then it compiled successfully when I exit conda environment, Python==3.7.2 in the same time. 
Thanks for reply.
