### ISSUE TITLE
About Pre-trained Model

### ISSUE THREAD

**Issue by gmltmd789** [cantabile-kwok/VoiceFlow-TTS#4]
Hello,

First of all, thank you for sharing the code!

I was wondering if you have any plans to release a pre-trained model trained on LibriTTS.

**Comment by cantabile-kwok** [comment]
Thank you for your interest in this work. To be honest we currently do not have the plan to release the pretrained model, as it is still an elementary version and needs to be further improved. Plus, the xvector we used for training LibriTTS model requires some tedious procedures to extract, which we are planning to replace in the future. Sorry for the inconvenience, and if you have any questions for training the model, please do let us know : )

**Comment by gmltmd789** [comment]
Thank you for your response :)
