### ISSUE TITLE
synthesis quality

### ISSUE THREAD

**Issue by forwiat** [cantabile-kwok/VoiceFlow-TTS#5]
Hi author, I attempt to train VoiceFlow in aishell3 dataset, but some noise appeared in synthesized audio.
Maybe it because of english vocoder?

**Comment by cantabile-kwok** [comment]
Yes, the vocoder might be mismatched, since we only provided the HifiGAN trained on LJspeech. If you choose to train on AIShell3, it is recommended to use a Chinese vocoder trained on that, or a universal one.

By the way, could you provide some audio samples with noise, so that we can diagnose?

**Comment by cantabile-kwok** [comment]
I would like to add another note: the mel-spectrogram features for training the TTS model must match the ones used for training the vocoder. So if you use another vocoder whose input mel-spectrograms have different parameters (e.g. different frame shift, window length, etc.), it is not necessary to run the feature extraction scripts provided in this repo : )

**Comment by forwiat** [comment]
yeah, I noticed this section, I will try it again. Thanks for tips! In addition, Maybe I have no permission? I can't upload wav files or picture in comment.

**Comment by cantabile-kwok** [comment]
Oh that's a limitation by github. Maybe next time you can try upload to google drive and paste the links here if necessary

**Comment by forwiat** [comment]
Ok, I try to train a new vocoder to judge whether dataset field mismatch.
